version: "3"

services:
  selenium:
    image: selenium/standalone-chrome:latest # selenium公式
    shm_size: 2gb # ホストとメモリを共有するために設定
    ports:
      - 4444:4444 # selenium sever port
      - 7900:7900
    container_name: selenium

  python3:
    #image: python:3.10
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/selenium
    tty: true
    ports:
      - 5000
    container_name: python3
    depends_on: # seleniumコンテナの後で起動させるように指定
      - selenium

networks:
  test_db:
    external: true
  selenium:
    external: true
